name: fl-health
channels:
  - conda-forge
  - defaults
dependencies:
  # Base Python
  - python=3.10
  - pip
  
  # Core Machine Learning
  - tensorflow=2.11.0
  - scikit-learn=1.2.0
  - numpy=1.24.0
  - pandas=2.0.0
  - scipy=1.10.0
  
  # Federated Learning Frameworks (via pip)
  - pip:
    - tensorflow-federated==0.72.0
    - flwr==1.8.0
    - syft==0.8.0
    - openfl==1.5.0
    - substra==0.36.0
  
  # Data Processing & Visualization
  - matplotlib=3.7.0
  - seaborn=0.12.0
  - plotly=5.14.0
  - jupyter=1.0.0
  - notebook=6.5.2
  
  # Utilities
  - tqdm=4.65.0
  - python-dotenv=1.0.0
  - kaggle=1.5.12
  - pyyaml=6.0
  - requests=2.28.2
  
  # Development Tools
  - black=22.12.0
  - flake8=6.0.0
  - pylint=2.16.0
  - ipykernel=6.21.0